# Default values for Transmission.

image:
  repository: eclipse-mosquitto
  pullPolicy: IfNotPresent
  tag: 2.0.10

strategy:
  type: Recreate

services:
  main:
    port:
      port: 1883

env: {}

persistence:
  config:
    enabled: true
    mountPath: "/mosquitto"
    emptyDir: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""
