apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  settings.json: |
    {{- $dict := merge .Values.transmissionConfig .Values.transmissionFixedConfig }}
    {{- $dict | mustToPrettyJson | nindent 4 }}
