apiVersion: v1
description: Global, Versioned, peer-to-peer filesystem.
name: chia
version: 1.0.2
appVersion: 1.1.6
keywords:
- storage
- crypto
- blockchain
home: https://www.chia.net/
icon: https://www.chia.net/img/chia_logo.svg
sources:
- https://github.com/Chia-Network/chia-blockchain
- https://github.com/orgs/chia-network/packages/container/package/chia
dependencies:
  - name: common
    repository: file://../../../library/common/2104.0.0
    version: 2104.0.0
